### ISSUE TITLE
switch --dashboard

### ISSUE THREAD

**Issue by sciabarracom** [dilox/openwhisk#2]
se specificifichi --dashboard deve deployare anche la dashboard

**Comment by dilox** [comment]
intendi cosi'?
>python kubepass.py small 3 --dashboard
--dashboard è opzionale e nel caso che viene indicato esegue:

**Comment by sciabarracom** [comment]
si

**Comment by dilox** [comment]
https://github.com/dilox/openwhisk/commit/7b406174090c32ac5332bde61c293e645ed794ac
