### ISSUE TITLE
swicht --rook

### ISSUE THREAD

**Issue by sciabarracom** [dilox/openwhisk#3]
Se specififichi --rook deve depoyare anche rook

**Comment by sciabarracom** [comment]
per installare rook puoi convertire in python questo script https://github.com/sciabarracom/kubepass/blob/master/kinst/rook

**Comment by dilox** [comment]
ho capito, ci provo.
sia per --rook che per --dashboard metto gli opzionali kubectl -f etc. dopo il comando:
multipass exec kube-master -- wait-ready 4

**Comment by sciabarracom** [comment]
Si opzionali così questi completano il cluster con lo storage e la dashboard

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----
