### ISSUE TITLE
increementale

### ISSUE THREAD

**Issue by sciabarracom** [dilox/openwhisk#5]
deve essere incrementale

controlla che esiste il kube-master prima di ricrearlo
controlla che esiston i kube-node primaa di ricreearli
controllaa il namespace kubernetes-dashboard prima di ricreerlo
controlla il namespace rook prima di ricrearlo

**Comment by dilox** [comment]
ho fatto delle prove e sembra che gia' lo fa da solo.
se c'è gia il kube-master non lo riinstalla
se ci sono i nodi non li riinstalla
puoi anche aumentare i nodi (*ma non diminuirli*)
se trova la dashboard non la installa
se trova la rook non la installa
tu che ne dici?

Il giorno mer 17 lug 2019 alle ore 10:25 Michele Sciabarra <
notifications@github.com> ha scritto:

**Comment by sciabarracom** [comment]
E se ci sono nodi che mancano li aggiunge? Non deve diminuire...

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----

**Comment by dilox** [comment]
--
Pierluigi Di Lorenzo

Il gio 18 lug 2019, 08:24 Michele Sciabarra <notifications@github.com> ha
scritto:

> E se ci sono nodi che mancano li aggiunge? Non deve diminuire...
>

Se tu lo hai fatto da 1 eppoi gli dici ne voglio 2 allora ne crea un altro

Se ne hai 2 e gli dici ne voglio 1 ne lascia 2, non è che ne distrugge 1
